server:
  port: 8092

spring:
  application:
    name: service-autodeliver-nacos
  cloud:
    # nacos 配置
    nacos:
      # nacos discovery 服务注册中心
      discovery:
        # 集群节点信息
        #server-addr: 127.0.0.1:8851,127.0.0.1:8852,127.0.0.1:8853
        # 集群名称（默认为 default）
        #cluster-name: TD

        # 单机模式
        server-addr: 127.0.0.1:8848
        namespace: 42f37f6d-341a-49cb-87dc-35cb592c25aa   # 命名空间id

    # sentinel 配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 # sentinel dashboard 地址
        port: 8719   #  sentinel会在该端口启动 http server，控制台定义的一些限流等规则才能发送传递过来，如果8719端口被占用，那么会依次+1
      # Sentinel Nacos 数据源配置（Nacos 中的规则会自动同步到 sentinel 流控规则中）
      datasource:
        # 自定义 流控规则 数据源名称
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            namespace: 42f37f6d-341a-49cb-87dc-35cb592c25aa   # 命名空间id
            data-type: json
            rule-type: flow     # 类型来自 Sentinel 中的 RuleType 类
        # 自定义 降级规则 数据源名称
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            namespace: 42f37f6d-341a-49cb-87dc-35cb592c25aa   # 命名空间id
            data-type: json
            rule-type: degrade  # 类型来自 Sentinel 中的 RuleType 类


# springboot 中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always
