server:
  port: 9003

Spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          # 配置 git 服务地址
          uri: https://gitee.com/shorfng/cloud-config-repo.git
          # 配置 git 用户名
          username: shorfng@126.com
          # 配置 git 密码
          password: Freefree1007
          search-paths:
            - cloud-config-repo
      # 读取 git 分支
      label: main
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


# 将服务提供者注册到 Eureka 服务中心
eureka:
  client:
    service-url:
      # 注册到单实例（非集群模式），就写一个就可以
      # 注册到集群，把多个 Eureka server 地址使用逗号连接起来即可
      defaultZone: http://CloudEurekaServerA:8761/eureka,http://CloudEurekaServerB:8762/eureka
  instance:
    # 服务实例中显示 ip，而不是显示主机名（为了兼容老的 eureka 版本）
    prefer-ip-address: true
    # 自定义实例显示格式（加上版本号，便于多版本管理）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:0.0.1-SNAPSHOT

# 暴露通信端口
management:
  endpoints:
    web:
      exposure:
        # include: refresh
        # *表示暴露所有端口
        include: "*"

