# eureka server服务端口
server:
  port: 8762

spring:
  application:
    # 应用服务名称（会在Eureka中作为服务名称）
    name: cloud-eureka-server

# eureka 客户端配置（用于和Server交互），Eureka Server 其实也是一个 Client
eureka:
  instance:
    # 当前 eureka 实例的主机名
    hostname: CloudEurekaServerB
  client:
    service-url:
      # 配置客户端所交互的 Eureka Server 地址
      # Eureka Server集群中每一个Server其实相对于其它Server来说都是Client
      # 单机模式下
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群模式下，defaultZone 应该指向其它 Eureka Server，如果有更多其它Server实例，逗号拼接即可
      defaultZone: http://CloudEurekaServerA:8761/eureka
    # 是否禁止自己当做服务注册（集群模式下，可以改成 true）
    register-with-eureka: true
    # 是否屏蔽注册信息（默认为 true）
    # 单机模式下，自己就是 server，不需要从 EurekaServer 获取服务信息
    # 集群模式下，改成 true
    fetch-registry: true
  # 是否启用eureka服务控制台
  dashboard:
    enabled: true
